### ISSUE TITLE
[WIP] Checking specifications

### ISSUE THREAD

**Issue by takeshishimada** [cactacea/backend#160]
## Checking specifications

- [x] Change column name from postedAt to likedAt  `FeedLikes` `CommentLikes` .
- [x] Remove profile properties from PostSignUp.
- [x] Add reportedAt property. `AccountReports``CommentReports``FeedReports``GroupReports`
- [ ] ~~Check how to use `udid`.~~ #163
- [x] Add last_posted_at column to `groups` table.
- [ ] ~~Add file upload feature to POST `/sessions`~~ #162
- [ ] Change `displayName` property from Option[String] to String
- [x] ~~Add `displayName` sorting~~  #161
- [x] Change `editedDisplayName` to `displayName`
